apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
